### ISSUE TITLE
Linking to awesome-ocaml for the ecosystem

### ISSUE THREAD

**Issue by kalouantonis** [bluddy/ocamlverse#15]
I spoke with some users on IRC and the opinion is that we've already duplicated awesome-ocaml and it would be better, rather than fragmenting that resource to just link to it and submit PR's for updating content.

Lots of people look for awesome lists when starting with a language anyway and it might be a better way to maintain these resources in one place.

What's your opinion?

**Comment by bluddy** [comment]
I think awesome-ocaml is a great resource, but it's not very comprehensive or in-depth -- it can't be. It was a good starting point for ocamlverse, because I think having content gets contribution going in a way that an empty site does not. But there's a reason I re-categorized the content from awesome-ocaml and split it up -- the one page convention is confusing (IMO) and prevents any meaningful information from being conveyed.

ocamlverse is essentially a modern wiki. Notice that you have both [awesome-haskell](https://github.com/krispo/awesome-haskell) and the [haskell wiki](https://wiki.haskell.org/Applications_and_libraries), and they both list libraries and applications. The wiki, however, can go into much more depth.

Additionally, people in our community tend to think that any effort is a zero-sum game. This may be because we've been burned by having several standard libraries, several build tools etc. I don't think, however, that this applies to community-building, and unfortunately, some members of our community don't get that. Whichever way you get people excited about contributing to the community proceeds to cause more excitement, which gets more people involved. It's a feedback loop.

Another relevant factor is that we're now the tail end of a language (reason) that's truly going viral. We have the choice of staying stagnant and getting passed over as a relic, or using that lottery ticket we just won to enhance and enlarge our community.

The goals of ocamlverse are to document everything in the ocaml world (including its ecosystem), and to encourage excitement in the community about documentation. Assuming it succeeds, there will be more energy and people to update ocaml.org as well as awesome-ocaml as needed. I certainly don't mind if anyone wants to copy the ecosystem content of ocamlverse back into awesome-ocaml occasionally, reducing the content as needed to make it fit the awesome-ocaml format. But that clearly doesn't suggest that awesome-ocaml approaches the mission statement of ocamlverse.

**Comment by ivg** [comment]
I  also would like to add that ocamlverse at this stage looks like awesome-ocaml. But this is only the first step, they will diverge in the future.

**Comment by kalouantonis** [comment]
I'm closing this because I generally agree with your opinions.

I just wanted to clear up in a slightly more formal way why this project exists, since I had to answer those questions by the IRC people.
